[package]
name = "demos_glutin"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
glutin = "*"
nalgebra = "*"
num-traits = "0.2"
rand = "*"

# del-msh = {path="../del-msh"}
del-msh = "*"
del-ls = "*"
del-dtri = "*"
del-misc = "*"

[build-dependencies]
gl_generator = "*"